// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nohesgxbswbpfevrlhrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vaGVzZ3hic3dicGZldnJsaHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzAxODEsImV4cCI6MjA2OTc0NjE4MX0._q4r5qbjC22s4qJVqOKXuY2YfjHKMkh-o46LYwWP0JE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});